import * as monaco from 'monaco-editor';

export const NeuralDSLTheme = {
  dark: {
    base: 'vs-dark' as const,
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'C586C0', fontStyle: 'bold' },
      { token: 'keyword.hpo', foreground: 'DCDCAA', fontStyle: 'bold' },
      { token: 'keyword.boolean', foreground: '569CD6' },
      { token: 'keyword.null', foreground: '569CD6' },
      { token: 'type.layer', foreground: '4EC9B0', fontStyle: 'bold' },
      { token: 'type.optimizer', foreground: 'CE9178' },
      { token: 'type.schedule', foreground: 'D4A5A5' },
      { token: 'identifier.layer-name', foreground: '9CDCFE', fontStyle: 'italic' },
      { token: 'identifier.parameter', foreground: '9CDCFE' },
      { token: 'identifier', foreground: 'D4D4D4' },
      { token: 'string', foreground: 'CE9178' },
      { token: 'string.escape', foreground: 'D7BA7D' },
      { token: 'string.invalid', foreground: 'F44747' },
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'number.float', foreground: 'B5CEA8' },
      { token: 'operator', foreground: 'D4D4D4' },
      { token: 'operator.device', foreground: 'FFC66D', fontStyle: 'bold' },
      { token: 'operator.multiply', foreground: 'C586C0' },
      { token: 'delimiter', foreground: 'D4D4D4' },
    ],
    colors: {
      'editor.background': '#1E1E1E',
      'editor.foreground': '#D4D4D4',
      'editor.lineHighlightBackground': '#2A2A2A',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#3A3D41',
      'editorCursor.foreground': '#AEAFAD',
      'editorWhitespace.foreground': '#404040',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#C6C6C6',
      'editorBracketMatch.background': '#0064001A',
      'editorBracketMatch.border': '#888888',
      'editorError.foreground': '#F44747',
      'editorWarning.foreground': '#CCA700',
      'editorInfo.foreground': '#3794FF',
    }
  } as monaco.editor.IStandaloneThemeData,

  light: {
    base: 'vs' as const,
    inherit: true,
    rules: [
      { token: 'comment', foreground: '008000', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'AF00DB', fontStyle: 'bold' },
      { token: 'keyword.hpo', foreground: '795E26', fontStyle: 'bold' },
      { token: 'keyword.boolean', foreground: '0000FF' },
      { token: 'keyword.null', foreground: '0000FF' },
      { token: 'type.layer', foreground: '267F99', fontStyle: 'bold' },
      { token: 'type.optimizer', foreground: 'A31515' },
      { token: 'type.schedule', foreground: '811F3F' },
      { token: 'identifier.layer-name', foreground: '001080', fontStyle: 'italic' },
      { token: 'identifier.parameter', foreground: '001080' },
      { token: 'identifier', foreground: '000000' },
      { token: 'string', foreground: 'A31515' },
      { token: 'string.escape', foreground: 'EE9900' },
      { token: 'string.invalid', foreground: 'CD3131' },
      { token: 'number', foreground: '098658' },
      { token: 'number.float', foreground: '098658' },
      { token: 'operator', foreground: '000000' },
      { token: 'operator.device', foreground: 'AF00DB', fontStyle: 'bold' },
      { token: 'operator.multiply', foreground: 'AF00DB' },
      { token: 'delimiter', foreground: '000000' },
    ],
    colors: {
      'editor.background': '#FFFFFF',
      'editor.foreground': '#000000',
      'editor.lineHighlightBackground': '#F0F0F0',
      'editor.selectionBackground': '#ADD6FF',
      'editor.inactiveSelectionBackground': '#E5EBF1',
      'editorCursor.foreground': '#000000',
      'editorWhitespace.foreground': '#D3D3D3',
      'editorLineNumber.foreground': '#237893',
      'editorLineNumber.activeForeground': '#0B216F',
      'editorBracketMatch.background': '#0064001A',
      'editorBracketMatch.border': '#B9B9B9',
      'editorError.foreground': '#E51400',
      'editorWarning.foreground': '#BF8803',
      'editorInfo.foreground': '#1A85FF',
    }
  } as monaco.editor.IStandaloneThemeData
};
